# Generated by Django 2.1 on 2019-06-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('price', models.FloatField(default=1)),
                ('description', models.TextField(max_length=500, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
